api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:     ['application/json']
    swagger:
        versions: [2]
        api_keys:
             apiKey:
                name: Authorization
                type: header
